/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.aes.patrones;

public class Main {
    
    public static void main(String[] args) throws Exception {

        var point = new Point(10, 10);
        System.out.println("Cuerrent: " + point);

        var y = Point.class.getDeclaredField("y");
        y.setAccessible(true);
        y.set(point, 5);
        System.out.println("New: " + point);
    }
}
