/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.aes.patrones;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    
    @Test 
    void emptyGreeting() {
        
    }
}
