global:
  scrape_interval: 15s
  external_labels:
    monitor: 'exchange-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['currency-exchange-quarkus:8080', 'product-catalogue-quarkus:8080']
