/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.aes.patrones;

import java.lang.reflect.*;

public class Main {
    

    public static void main(String[] args) throws Exception {
        var point = new Point(10, 10);
        var clazz = point.getClass();
        
        System.out.println(clazz.getName());
        System.out.println("Current val: " + point);

        var x = clazz.getDeclaredField("x");
        x.setAccessible(true);
        x.set(point, 5);
        System.out.println("New val: " + point);
    }
}
