/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.pica.jvm.performance;

public class Main {

    public static void main(String[] args) {
        int value = 10;
        value = power2(value);
    }

    public static int power2(int number) {
        int result = number * number;
        return result;
    }
}
