#%RAML 1.0
---
title: "Pagos Domiciliacion"
baseUri: http://some-public-url.com/api/domiciliacion
version: "v1"

/factura:
    get:
        description: "Retorna la info de la factura dado el fid como un query param"
        queryParameters:
            fid:
                type: string
                required: true
                example: "ABCD12345"
        responses:
            200:
                body:
                    application/json:
                        schema: !include factura.json
    post:  
        description: "Realiza el pago dado el fid y el valor a pagar en el cuerpo del mensaje"
        body:
            application/json:
                schema: !include factura.json
        responses:
            200:
                application/json:
                    schema: !include factura.json
    patch:
        description: "Realiza el el cambio de estado de la factura dada el fid y estado PENDIENTE"
        body:
            application/json:
                schema: !include factura.json
        responses:
            200:
                application/json:
                    schema: !include factura.json