//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 09:14:27 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.javeriana.edu.co/aes/modval/services")
package co.edu.javeriana.aes.modval.helloworld.entity;
