/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.pica.jvm.performance.mls;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
}
