/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.aes.patrones;

import java.lang.reflect.*;

public class Main {
    
    @Inject
    private Bean bean;

    public Bean getBean() {
        return bean;
    }

    public static void main(String[] args) throws Exception {

        var main = new Main();


        var fields = Main.class.getDeclaredFields();
        for (Field field : fields) {
            var annotation = field.getAnnotation(Inject.class);
            if (annotation != null) {
                var type = field.getType();
                var instance = type.newInstance();

                field.setAccessible(true);
                field.set(main, instance);
            }
        }

        System.out.println(main.getBean());
    }
}
