#%RAML 1.0
---
title: etb-mobile
baseUri: http://host:port/api/resources
version: v1

/facturacion:
  get:
    description: Obtiene la info básica de una Factura de acuerdo a su Factura
    queryParameters:
      referencia-pago:
        displayName: Referencia
        description: Referencia de Pago de la Factura
        required: true
    responses:
      200:
        body:
          application/json:
            schema: !include factura.json
            example: !include sample.json
      500:
        body:
          application/json:
            schema: !include error.json
  post:
    description: Realiza el pago de la factura de acuerdo a su Referencia
    queryParameters:
      referencia-pago:
        displayName: Referencia
        description: Referencia de Pago de la Factura
        required: true
    responses:
      200:
        body:
          application/json:
            schema: !include factura.json
            example: !include sample.json
      500:
        body:
          application/json:
            schema: !include error.json
  put:
    description: Realiza una compensación de la factura de acuerdo a su Referencia
    queryParameters:
      referencia-pago:
        displayName: Referencia
        description: Referencia de Pago de la Factura
        required: true
    responses:
      200:
        body:
          application/json:
            schema: !include factura.json
            example: !include sample.json
      500:
        body:
          application/json:
            schema: !include error.json