/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.javeriana.aes.patrones;

/**
 * @author German Suárez - german.suarez@javeriana.edu.co
 */
public class Main {
    
    public static void main(String[] args) throws Exception {
        var simpleHttpServer = new SimpleHttpServer();
        simpleHttpServer.start();
        simpleHttpServer.join();
    }
}
