
package co.edu.javeriana.aes.modval.pagos.artifacts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiciosPagos", targetNamespace = "http://www.servicios.co/pagos/service", wsdlLocation = "file:/Users/gersua/Projects/UJaveriana-AES-ModVal/Workshop1-SOAP-Service/src/main/resources/co/edu/javeriana/aes/modval/pagos.wsdl")
public class ServiciosPagos
    extends Service
{

    private final static URL SERVICIOSPAGOS_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSPAGOS_EXCEPTION;
    private final static QName SERVICIOSPAGOS_QNAME = new QName("http://www.servicios.co/pagos/service", "ServiciosPagos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/gersua/Projects/UJaveriana-AES-ModVal/Workshop1-SOAP-Service/src/main/resources/co/edu/javeriana/aes/modval/pagos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSPAGOS_WSDL_LOCATION = url;
        SERVICIOSPAGOS_EXCEPTION = e;
    }

    public ServiciosPagos() {
        super(__getWsdlLocation(), SERVICIOSPAGOS_QNAME);
    }

    public ServiciosPagos(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSPAGOS_QNAME, features);
    }

    public ServiciosPagos(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSPAGOS_QNAME);
    }

    public ServiciosPagos(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSPAGOS_QNAME, features);
    }

    public ServiciosPagos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosPagos(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PagosInerface
     */
    @WebEndpoint(name = "Pagos")
    public PagosInerface getPagos() {
        return super.getPort(new QName("http://www.servicios.co/pagos/service", "Pagos"), PagosInerface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagosInerface
     */
    @WebEndpoint(name = "Pagos")
    public PagosInerface getPagos(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.servicios.co/pagos/service", "Pagos"), PagosInerface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSPAGOS_EXCEPTION!= null) {
            throw SERVICIOSPAGOS_EXCEPTION;
        }
        return SERVICIOSPAGOS_WSDL_LOCATION;
    }

}
