//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 10:28:47 AM COT 
//


package co.edu.javeriana.aes.modval.timestamp.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/** Auto-generated class based on the canonical representation for Timestamp
 * xjc -d Timestamp/src/main/java/co/edu/javeriana/aes/modval/timestamp/entity
 *    -p co.edu.javeriana.aes.modval.timestamp.entity Timestamp.xsd */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Timestamp", propOrder = {
        "currentTS"
})
public class Timestamp {

    protected long currentTS;

    public Timestamp() {}

    public Timestamp(long currentTS) {
        this.currentTS = currentTS;
    }

    /**
     * Gets the value of the currentTS property.
     */
    public long getCurrentTS() {
        return currentTS;
    }
}
